name: Ruff Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ruff:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ruff check
        uses: astral-sh/ruff-action@v3
        with:
          # Runs `ruff check .` on your whole repository.
          args: "check ."
      - name: Run Ruff formatter
        uses: astral-sh/ruff-action@v3
        with:
          # Checks for any format needs.
          args: "format --check"
